### ISSUE TITLE
Restore COPYING

### ISSUE THREAD

**Issue by jamesjer** [lbfm-rwth/carat#33]
The old tarball had a COPYING file containing the text of GPLv3.  That file did not make the transition to github, it seems.

**Comment by alex-konovalov** [comment]
Thanks - this will also tick a box in #1. Where is the old tarball so we can check?

**Comment by jamesjer** [comment]
I'm afraid I don't know how to find the old tarball anymore.  I've got a copy I downloaded in 2015 for the purposes of creating a carat package for Fedora.  It's up in the Fedora build system, but I don't know if there is a way for the general public to access it.  If you know how to unpack an RPM, you can get it out of the latest build: https://kojipkgs.fedoraproject.org/packages/carat/2.1b1.19.07.2008/13.fc31/src/carat-2.1b1.19.07.2008-13.fc31.src.rpm

**Comment by alex-konovalov** [comment]
Indeed https://web.archive.org/web/20160817084957/http://wwwb.math.rwth-aachen.de/carat/carat.tgz has COPYING with GPLv3. Perhaps there were different archives lying around when this repository was created...

**Comment by jamesjer** [comment]
Oh yes, I remember now.  On May 18, 2015 I sent an email to the carat maintainers with a few patches, and I asked about the license at that time.  They created a new tarball on May 21 with the license file and the patches applied, but did not change either the version number or the name of the tarball.  I thought at the time that that was a bad idea....

**Comment by gaehler** [comment]
My GAP package Carat version 2.2.3 contains that tarball, including the COPYING file.

**Comment by alex-konovalov** [comment]
Glad that we have evidence and memories :) Is there anything else in that tarball? What about those few patches - are they still relevant, already applied, or obsolete?

**Comment by jamesjer** [comment]
Kind of a mix, I'm afraid.  Some parts were fixed anew in the recent warning cleanup commit, some are still as they were originally.  I just submitted pull request 34, which applies the rest and does some additional warning cleanup.

**Comment by fingolfin** [comment]
I just merged PR #34 (didn't even know I had the permissions to do that ;-).

We actually got permission to put this code under GPL 2 or later, so I think we should do that. I just created PR #39 to this end
