### ISSUE TITLE
Migrate AppVeyor setup

### ISSUE THREAD

**Issue by fingolfin** [lbfm-rwth/carat#50]
Right now, the AppVeyor builds are run under @alex-konovalov's personal account there. This should be changed. It's been some time since I last did this, but I believe the right way to do this is to go to https://github.com/marketplace/appveyor and then add AppVeyor with its open-source plan to the lbfm-rwth organization. However, somebody with admin access to the org needs to do that. Once this has been done, the AppVeyor webhook under https://github.com/lbfm-rwth/carat/settings/hooks can be removed. I think that's all that is needed, but there might be more -- again, it's been some time I last did this.

**Comment by DominikBernhardt** [comment]
@fingolfin I think I did everything correctly. Let's see if everything works fine with a new PR.

**Comment by DominikBernhardt** [comment]
This work now, so I'll close the issue.
