### ISSUE TITLE
cozycle?

### ISSUE THREAD

**Issue by fingolfin** [lbfm-rwth/carat#69]
There are tons of occurrences of `cozycle` in the code; but also `cocycle` is used. So is `cozycle` simply a pervasive typo, or is this defined to be something "clever" in the context of carat, like "a cocycle with special properties / of a special kind of object"? If it's a typo, let's fix that; if it's intentional, it should be documented (maybe it is, but I couldn't find it).

**Comment by gaehler** [comment]
I'm quite sure this is just a Germanism, and can be corrected.
