### ISSUE TITLE
TSupergroups segmentation fault

### ISSUE THREAD

**Issue by gaehler** [lbfm-rwth/carat#8]
On the attached input file `IT88.txt`, the command `TSupergroups IT88.txt -t` consistently produces a segmentation fault. The same happens with many other input files. I couldn't figure out what the problem is. 
[IT88.txt](https://github.com/lbfm-rwth/carat/files/2624720/IT88.txt)

**Comment by gaehler** [comment]
It looks as if the code cleanup of PR #34 fixed this bug. At least, the segfault seems gone. Thanks to  @jamesjer!

**Comment by fingolfin** [comment]
Actually this still crashes for me on macOS.
